[build]
  publish = "."
  command = "echo 'Static site ready for deployment'"

[[redirects]]
  from = "/templates/builder"
  to = "/templates/template_builder.html"
  status = 200

[[redirects]]
  from = "/templates"
  to = "/templates/templates_list.html"
  status = 200

[[redirects]]
  from = "/correction"
  to = "/templates/correction.html"
  status = 200

[[redirects]]
  from = "/reports"
  to = "/templates/reports.html"
  status = 200

[[redirects]]
  from = "/analytics"
  to = "/templates/analytics.html"
  status = 200

[[redirects]]
  from = "/settings"
  to = "/templates/settings.html"
  status = 200

[[redirects]]
  from = "/help"
  to = "/templates/help.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/templates/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
